name: blue_bird_scanner
description: A Flutter plugin for barcode scanning with BlueBird PDAs.
version: 2.0.1+5
homepage: https://github.com/luis901101/blue_bird_scanner

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.flutter.bluebirdscanner
        pluginClass: BlueBirdScannerPlugin
